"""
Provenance tracking for versioned documents.

Tracks document version lineage including unsubmitted drafts to maintain
complete document history even for versions that were never submitted.
"""

import os
import re
import logging
from pathlib import Path
from typing import Dict


class ProvenanceTracker:
    """Tracks document version lineage including unsubmitted drafts."""

    def __init__(self, config: Dict):
        """
        Initialize provenance tracker.

        Args:
            config: Sync configuration dict containing project paths
        """
        self.config = config
        self.logger = logging.getLogger(__name__)

    def track_unsubmitted_draft(
        self,
        replace_info: Dict,
        project_path: str,
        filename: str
    ) -> None:
        """
        Record unsubmitted draft in provenance file.

        Creates or appends to a provenance file documenting versions that
        were replaced but never submitted to the repository.

        Args:
            replace_info: Dict containing version, status, reason, note, etc.
            project_path: Root path of the project
            filename: Current file name (used to derive provenance filename)
        """
        basename = os.path.splitext(filename)[0]

        # Remove version suffix from basename for provenance file
        basename_clean = re.sub(r'-v?\d+\.\d+(?:\.\d+)?$', '', basename)

        provenance_dir = os.path.join(project_path, 'docs', 'provenance')
        provenance_file = os.path.join(provenance_dir, f"{basename_clean}.provenance.md")

        # Ensure provenance folder exists
        Path(provenance_dir).mkdir(parents=True, exist_ok=True)

        # Create or append to provenance file
        if not os.path.exists(provenance_file):
            with open(provenance_file, 'w', encoding='utf-8') as f:
                f.write(f"# Document Provenance: {basename_clean}.md\n\n")
                f.write("**Auto-generated by deia sync**\n")
                f.write("**Purpose:** Track complete document lineage including unsubmitted drafts\n\n")
                f.write("---\n\n")
                f.write("## Version Lineage\n\n")

        # Append unsubmitted draft entry
        with open(provenance_file, 'a', encoding='utf-8') as f:
            version = replace_info.get('version', 'unknown')
            f.write(f"### v{version} ({replace_info.get('superseded_date', 'unknown')})\n")
            f.write(f"- **Status:** UNSUBMITTED DRAFT\n")
            f.write(f"- **Location:** Never received\n")
            if 'reason' in replace_info:
                f.write(f"- **Reason:** {replace_info['reason']}\n")
            if 'note' in replace_info:
                f.write(f"- **Note:** {replace_info['note']}\n")
            f.write(f"- **Evidence:** Declared in replaces field of subsequent version\n\n")

        self.logger.info(f"Tracked unsubmitted draft v{version} in provenance for {basename_clean}")
