#!/bin/bash
# DEIA Setup Commands - Run these to complete setup

echo "=== DEIA Setup ==="
echo ""
echo "Step 1: Push to GitHub"
echo "----------------------"
echo "cd C:\Users\davee\OneDrive\Documents\GitHub\deiasolutions"
echo "git status  # Verify only public files"
echo "git add -A"
echo "git commit -m 'Initial public release: Conversation logging + BOK structure'"
echo ""
echo "# Create repo on GitHub first: https://github.com/new"
echo "# Name: deia"
echo "# Public repo"
echo "# Do NOT initialize"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/deia.git"
echo "git push -u origin master"
echo ""
echo ""
echo "Step 2: Verify .gitignore working"
echo "----------------------------------"
echo "git status  # Should NOT show: .deia/, admin/, project_resume.md"
echo ""
echo ""
echo "✅ GitHub setup complete!"
